export const EVIDENCE_BY_ID: Record<string, string> = {
	'lezen-2025-1': "Ruud Kaag is timmerman en al sinds zijn 17e werkzaam in de bouwsector. Zijn beroep als timmerman heeft hij 45 jaar uitgevoerd. Binnenkort stopt hij echter bij zijn huidige werkgever.",
	'lezen-2025-2': "Ruud vindt het een goede zaak dat mensen in de sector regelmatig medisch onderzocht worden.",
	'lezen-2025-3': "Ik heb een collega van 35 jaar, die al geopereerd is aan zijn rug.",
	'lezen-2025-4': "Maar als je heel goed je best doet, lukt het echt wel.",
	'lezen-2025-5': "Ruud nam het initiatief tot omscholing zelf.",
	'lezen-2025-6': "Ruud Kaag is timmerman en al sinds zijn 17e werkzaam in de bouwsector.",
	'lezen-2025-7': "Dieren hebben ook traanklieren, maar je zal ze niet zien huilen van emotie.",
	'lezen-2025-8': "Gedragswetenschappers geven aan dat huilen bij volwassenen ook die functie heeft.",
	'lezen-2025-9': "Ook zijn de traanbuizen (kleine buisjes die de tranen afvoeren) van mannen kleiner dan die van vrouwen, waardoor ze moeilijker kunnen huilen.",
	'lezen-2025-10': "Ook komen er tijdens het huilen in het lichaam zelf gelukshormonen vrij, zoals endorfinen, die je kalm maken.",
	'lezen-2025-11': "Lees verder voor een paar leuke weetjes over huilen en een kleine ode aan een traantje op zijn tijd.",
	'lezen-2025-12': "Huilen wordt in onze Westerse maatschappij meestal niet zo gewaardeerd.",
	'lezen-2025-13': "Dan is het tijd om op hem af te stappen en te kijken of je hem kunt helpen.",
	'lezen-2025-14': "Je stelt eerst gerichte vragen om erachter te komen wat hij wil en waarom.",
	'lezen-2025-15': "Het is belangrijk dat je weet welke service jouw bedrijf kan bieden.",
	'lezen-2025-16': "Maar vergeet niet dat jouw vriendelijke houding het meest bijdraagt aan een goed imago.",
	'lezen-2025-17': "Het is dan heel erg belangrijk dat je de klant serieus neemt.",
	'lezen-2025-18': "Hoe goed je product ook is, als je geen klanten in je winkel krijgt, moet je bedrijf uiteindelijk de deuren sluiten.",
	'lezen-2025-19': "Uren die u werkt buiten het dienstrooster, maar binnen de 8 werkuren per dag, worden ‘verschoven uren’ genoemd.",
	'lezen-2025-20': "Als u overwerkt tot 24.00 uur na een volle werkdag hoeft u de eerste 11 uren na het overwerk niet te werken.",
	'lezen-2025-21': "Als u 55 jaar of ouder bent, kan u verplicht worden tot maximaal 5 uren overwerk in een periode van vier weken.",
	'lezen-2025-22': "Dat kan op verschillende manieren: 1) uren kunnen in geld worden vergoed; 2) uren kunnen met een maximum van 10 dagen per jaar in vrije tijd worden vergoed.",
	'lezen-2025-23': "Overwerk wordt extra beloond. Er is echter wel een aantal regels en uitzonderingen.",
	'lezen-2025-24': "Deze speciale whatsappgroepen zijn vaak bedoeld om verdachte situaties te melden aan buurtgenoten.",
	'lezen-2025-25': "Aanleiding was een poging tot inbraak bij haar thuis.",
	'lezen-2025-26': "“Het is niet verantwoord als mensen zelf politie gaan spelen”, zegt Wajid.",
	'lezen-2025-27': "Een buurt-whatsapp is niet bedoeld voor oproepjes, dus af en toe grijp ik in.",
	'lezen-2025-28': "De buurt-whatsapp dient zo’n serieus doel.",
	'lezen-2025-29': "Wanneer je niet op school of stage aanwezig kunt zijn, dien je dit voor 09.00 uur ’s ochtends te melden bij het Onderwijsservicebureau (OSB) van jouw sector (via het nummer dat op de belkaart staat) en indien van toepassing ook bij je stagebedrijf.",
	'lezen-2025-30': "Je scant je pas bij de toegangspoortjes bij de ingang. Hierdoor registreer je dat je in het gebouw aanwezig bent. Bij aanvang van de les registreert de docent of je aanwezig bent.",
	'lezen-2025-31': "Zie je dat er ergens brand is of dat een andere gevaarlijke situatie zich voordoet en heb je nog geen alarmsignaal gehoord, waarschuw dan een conciërge of de receptie.",
	'lezen-2025-32': "Je moet wettelijk cursusgeld betalen als je een BBL-opleiding volgt en op 1 augustus 18 jaar of ouder bent.",
	'lezen-2025-33': "Voor komend schooljaar is dit:\n▪ € 236,00 voor niveau 1 of 2\n▪ € 573,00 voor niveau 3 of 4 Ook vavo-studenten die een opleiding volgen van minder dan 29 lesuren en via de rijksoverheid bekostigd worden, moeten wettelijk cursusgeld betalen: € 30,- per lesuur.",
	'lezen-2025-34': "Je betaalt daarvoor € 5,- administratiekosten.",
	'lezen-2025-35': "Als je de gewonde persoon niet kunt of durft te verplaatsen, blijf je altijd bij hem of haar en laat je iemand anders de receptie of conciërge waarschuwen.",
	'lezen-2024-1': "In de centrale bakkerij hebben we drie afdelingen; de afdeling ‘korstgebak’ waar bijvoorbeeld saucijzenbroodjes worden gemaakt, de deegafdeling waar onder andere appeltaarten worden gemaakt en de beslagafdeling waar de basis voor bijvoorbeeld de fototaarten wordt gemaakt.",
	'lezen-2024-2': "Af en toe wordt ook ’s nachts doorgewerkt.",
	'lezen-2024-3': "Heb je gevoel voor techniek, vind je het leuk om met machines te werken en heb je affiniteit met gebak, dan is dit de plek voor jou.",
	'lezen-2024-4': "Als nieuwe medewerker start je met eenvoudige werkzaamheden.",
	'lezen-2024-5': "• De afdeling inkoop zorgt dat alle ingrediënten en verpakkingsmaterialen aanwezig zijn, zodat de bakkerijen zich hier niet druk om hoeven te maken.",
	'lezen-2024-6': "Ruim 250 medewerkers van onze centrale bakkerij in Utrecht en onze zes decentrale bakkerijen in het hele land werken met veel liefde en op traditionele wijze aan onze taarten, snacks en andere bakkerijproducten, zodat die altijd vers in de winkels staan.",
	'lezen-2024-7': "De meeste mogelijkheden biedt een eilandstand: een afgescheiden ruimte met looppaden er omheen.",
	'lezen-2024-8': "Met de organisator overleg je waar de stand precies komt: op welk deel van de beurs?",
	'lezen-2024-9': "Mensen kijken onbewust naar verlichte gedeeltes, dus je wilt meer licht achterin of in het centrum.",
	'lezen-2024-10': "Dus zorg voor een goede voorbereiding: laat je zakelijke kennissen weten dat je er zult zijn!",
	'lezen-2024-11': "Op een beurs moeten de aanbieders ruimte huren van de organisator.",
	'lezen-2024-12': "Het wordt anders als een werknemer zes weken of langer ziek is.",
	'lezen-2024-13': "Dit heet een re-integratietraject. Jouw bedrijf moet de kosten voor het re-integratietraject betalen.",
	'lezen-2024-14': "Soms volstaat een goed gesprek om de ruzies uit te praten, of is een kleine aanpassing in het werk al voldoende om de oorzaak van werkstress bij een werknemer weg te nemen.",
	'lezen-2024-15': "Grijs verzuim: Je werknemer is bijvoorbeeld licht verkouden en kan eigenlijk wel werken, maar meldt zich toch ziek.",
	'lezen-2024-16': "Als je werknemer herhaaldelijk geblesseerd raakt bij het sporten en hierdoor meermalen verzuimt, heb je als werkgever het recht hem formeel hierop te wijzen en hem te vragen met de sport te stoppen.",
	'lezen-2024-17': "Lees welke vormen van verzuim er zijn, wat je kunt doen om verzuim te voorkomen en hoe je de financiële risico’s zo goed mogelijk afdekt.",
	'lezen-2024-18': "Dat hoopt met de autosportklas jongeren warm te maken voor een technische opleiding, en mogelijk een carrière bij Defensie.",
	'lezen-2024-19': "Doorzettingsvermogen, discipline en motivatie zijn zeker zo belangrijk.",
	'lezen-2024-20': "De grootste uitdaging is om het vol te houden, in dit geval ook financieel.",
	'lezen-2024-21': "Hussam zat aanvankelijk op niveau 3, ‘maar toen ik hoorde van de autosportklas, heb ik mijn best gedaan om toch niveau 4 te halen.’",
	'lezen-2024-22': "Het is onhandig dat het raceseizoen één kalenderjaar loopt, waardoor het extra jaar raceklas noodgedwongen is uitgesmeerd over twee schooljaren: het tweede en het derde jaar.",
	'lezen-2024-23': "Marelis: ‘Want de voertaal in de racewereld is Engels.",
	'lezen-2024-24': "De autosportklas van Newton College is een extra traject voor studenten van de opleiding motorvoertuigentechniek.",
	'lezen-2024-25': "Maar liefst 70 procent van de jongeren noemt zekerheid en stabiliteit als grootste wens.",
	'lezen-2024-26': "In de top 5 van de 45-plussers komt die wens niet eens voor.",
	'lezen-2024-27': "Veel 45-plussers hebben een financiële basis.",
	'lezen-2024-28': "Een vast contract heb je niet zomaar. Werkgevers kunnen steeds gemakkelijker van hun werknemers af.",
	'lezen-2024-29': "Van Veen adviseert werkgevers die zoeken naar jong personeel om rekening te houden met de uitkomsten van zijn onderzoek: “Je bereikt jonge werkzoekenden niet door alleen maar het avontuurlijke karakter van een baan te benadrukken.",
	'lezen-2024-30': "Jonge sollicitanten vinden arbeidsvoorwaarden belangrijker dan de inhoud van hun toekomstige werk.",
	'lezen-2024-31': "5.2 Opzeggen kan door het opzegformulier op www.wonderrijk.com/abonnementen in te vullen, te ondertekenen en te e-mailen naar abonnementen@wonderrijk.com of ingevuld en ondertekend per post te versturen naar Wonderrijk, Postbus 12, 5570 AA Bloemenoord, onder vermelding van “opzegging abonnement”, het abonnementsnummer en je adresgegevens.",
	'lezen-2024-32': "Dan stopt het na een jaar automatisch. Indien je een abonnement met maandelijkse betaling hebt afgesloten, loopt het abonnement na het eerste jaar door voor onbepaalde tijd.",
	'lezen-2024-33': "1.6 Eenieder voor wie of door wie een abonnement wordt aangeschaft bij de Gastenservice, dient zich te legitimeren.",
	'lezen-2024-34': "3.7 Parkeren met een parkeerabonnement is enkel toegestaan tijdens de reguliere openingstijden van het attractiepark.",
	'lezen-2024-35': "Indien je een abonnement met maandelijkse betaling hebt afgesloten, loopt het abonnement na het eerste jaar door voor onbepaalde tijd.",
	'lezen-2023-1': "De mbo-opleidingen van Ameda bereiden je dus voor op alle aspecten van een beroep!",
	'lezen-2023-2': "Een mbo-diploma van Ameda heeft dus exact dezelfde waarde als dat van bijvoorbeeld een ROC.",
	'lezen-2023-3': "Bovendien krijg je door Ameda ook een BPV-begeleider toegewezen.",
	'lezen-2023-4': "Dat kan via Ameda Campus, de digitale leeromgeving van Ameda!",
	'lezen-2023-5': "Je leert allerlei taken uit te voeren. Kies je bijvoorbeeld voor de opleiding Dierenartsassistent?",
	'lezen-2023-6': "Minstens twee keer per jaar bespreken de OR en de werkgever in de overlegvergadering de algemene gang van zaken van de onderneming.",
	'lezen-2023-7': "De werkgever moet de OR instemming vragen voor het vaststellen, wijzigen of intrekken van:\n• regelingen voor werktijden, vakantie, arbeidsomstandigheden, personeelsopleidingen, personeelsbeoordelingen;\n• regels voor het aanstellen, bevorderen of ontslaan van medewerkers;\n• een beloningssysteem of functiewaarderingssysteem;\n• een personeelsvolgsysteem of registratiesysteem;\n• de registratie van, omgang met en bescherming van persoonsgegevens;\n• regelingen voor ziekteverzuim.",
	'lezen-2023-8': "De Ondernemingskamer kan de werkgever verplichten het besluit in te trekken of de gevolgen ervan ongedaan te maken.",
	'lezen-2023-9': "De kantonrechter geeft alleen toestemming als:\n• de beslissing van de ondernemingsraad onredelijk is;\n• de werkgever zijn besluit neemt vanwege zwaarwegende redenen.",
	'lezen-2023-10': "De OR mag op eigen initiatief de werkgever voorstellen doen over alle sociale, organisatorische, financiële en economische zaken van de onderneming.",
	'lezen-2023-11': "Een ondernemingsraad (OR) bestaat uit werknemers die namens het personeel overleg voeren met de werkgever.",
	'lezen-2023-12': "Wie rijker wordt, wordt gelukkiger. Maar als een samenleving als geheel meer gaat verdienen, wordt daar niemand gelukkiger van.",
	'lezen-2023-13': "Een verklaring is gewenning: we gaan een betere levensstandaard al gauw als gewoon ervaren.",
	'lezen-2023-14': "Aan studenten werd gevraagd waaraan ze de voorkeur zouden geven: aan € 50.000 per jaar terwijl anderen de helft kregen, of aan € 100.000 per jaar terwijl anderen twee keer zoveel ontvingen.",
	'lezen-2023-15': "Aan dezelfde studenten werd ook gevraagd om te kiezen tussen twee weken vrij terwijl anderen slechts één week kregen, ofwel vier weken vrij terwijl anderen acht weken kregen.",
	'lezen-2023-16': "Dit blijkt uit onderzoek naar het verband tussen rijkdom en mate van geluksgevoel.",
	'lezen-2023-17': "Totdat ik een oproep zag om mee te doen aan een wedstrijd bij het Dolfinarium.",
	'lezen-2023-18': "Die vertrouwensband is echt iets moois!”",
	'lezen-2023-19': "Ondanks dat Emma niet echt een nadeel ervaart van haar baan, vindt ze de vis toch wel een minpuntje.",
	'lezen-2023-20': "Ook merken we dat ze gelukkig zijn. De dolfijnen paren en krijgen baby’s, en dat is een teken dat ze goed in hun vel zitten.",
	'lezen-2023-21': "“Zolang ik het hier leuk vind, blijf ik dit voorlopig nog even doen.",
	'lezen-2023-22': "Deze keer Emma. Zij is dolfijnentrainer!",
	'lezen-2023-23': "In eerste instantie wordt een buddy voor een jaar gekoppeld aan een cliënt.",
	'lezen-2023-24': "Buddyzorg is ontstaan in de jaren tachtig voor mensen met hiv en aids.",
	'lezen-2023-25': "Buddyzorg ontstond als begeleiding bij het sterven, maar tegenwoordig is de zorg veel meer gericht op hulp bij het verder leven.",
	'lezen-2023-26': "Dat vraagt om een buddy met levenservaring.",
	'lezen-2023-27': "De conclusie wordt open en eerlijk met de kandidaat besproken, ook wanneer hij niet geschikt blijkt.",
	'lezen-2023-28': "Deze tekst schetst wat een cliënt van een buddy verwacht en andersom: wat een buddy van een cliënt kan verwachten.",
	'lezen-2023-29': "Deelname is alleen voor de cursisten van Rosarius Opleidingen.",
	'lezen-2023-30': "Bij te laat komen beslist de examenleider of de kandidaat alsnog mag starten met het examen.",
	'lezen-2023-31': "Het is de kandidaat niet toegestaan het examenlokaal binnen 50 minuten na de start te verlaten.",
	'lezen-2023-32': "- Er mogen maximaal 2 verliespunten zijn behaald.",
	'lezen-2023-33': "Dit houdt in dat het resultaat niet alleen omhoog maar ook omlaag kan gaan of gelijk blijft.",
	'lezen-2023-34': "- Nederlands is niet de eerste taal. Wanneer de kandidaat korter dan vijf jaar in Nederland verblijft, heeft hij recht op 30 minuten extra examentijd. Hij mag ook een Nederlands handwoordenboek gebruiken.",
	'lezen-2023-35': "Deze examenwijzer is bedoeld voor docenten, examenleiders en examenkandidaten van Rosarius Opleidingen."
};

export function evidenceOf(id: string): string {
	const needle = EVIDENCE_BY_ID[id];
	if (!needle) throw new Error(`no evidence for ${id}`);
	return needle;
}
